[build]
dockerfile = "Dockerfile"
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"
nixpacksPlan = {"providers":["...","python"]}

[deploy]
command = "gunicorn app:app --bind 0.0.0.0:5000"
runtime = "V2"
numReplicas = 1
startCommand = "flask run"
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10