[build]
dockerfile = "Dockerfile"
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

# Corrigindo a tabela NIXPACKS
nixpacksPlan = { providers = ["...", "python"] }

[deploy]
command = "gunicorn app:app --bind 0.0.0.0:5000"
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn app:app --bind 0.0.0.0:5000"
sleepApplication = false

# Corrigindo a tabela multiRegionConfig
multiRegionConfig = { us-west2 = { numReplicas = 1 } }

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_APP = "app.py"
FLASK_ENV = "production"