[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"
nixpacksPlan = {"providers":["...","python"]}

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "flask run"
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10